package com.lucas.guis;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.lucas.Carioca_Digital.Jugador;
import com.lucas.Carioca_Digital.Ronda;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class menuJuego extends JFrame implements ActionListener {
    private JPanel panel1;
    private JButton volverAlMenúPrincipalButton;
    private JButton comenzarLaPartidaButton;
    private JComboBox rondaInicialComboBox;
    private JComboBox rondaFinalComboBox;
    private JComboBox nroJugadoresComboBox;
    private JTextField jugador1textField;
    private JTextField jugador2textField;
    private JTextField jugador3textField;
    private JTextField jugador4textField;

    public static void main(String[] args) {
        new menuJuego().setVisible(true);
    }

    public menuJuego() {

        add(panel1);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.pack();

        bloquearJTextFields();

        volverAlMenúPrincipalButton.addActionListener(this);
        comenzarLaPartidaButton.addActionListener(this);
        rondaInicialComboBox.addActionListener(this);
        rondaFinalComboBox.addActionListener(this);
        nroJugadoresComboBox.addActionListener(this);
        jugador1textField.addActionListener(this);
        jugador2textField.addActionListener(this);
        jugador3textField.addActionListener(this);
        jugador4textField.addActionListener(this);


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, BorderLayout.NORTH);
        volverAlMenúPrincipalButton = new JButton();
        volverAlMenúPrincipalButton.setText("Volver al menú principal");
        panel2.add(volverAlMenúPrincipalButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        comenzarLaPartidaButton = new JButton();
        comenzarLaPartidaButton.setText("Comenzar la partida");
        panel2.add(comenzarLaPartidaButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Comenzar una partida");
        panel2.add(label1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(12, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel3, BorderLayout.CENTER);
        rondaInicialComboBox = new JComboBox();
        panel3.add(rondaInicialComboBox, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Ronda inicial");
        panel3.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Ronda final");
        panel3.add(label3, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rondaFinalComboBox = new JComboBox();
        panel3.add(rondaFinalComboBox, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nroJugadoresComboBox = new JComboBox();
        panel3.add(nroJugadoresComboBox, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Número de jugadores");
        panel3.add(label4, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jugador1textField = new JTextField();
        panel3.add(jugador1textField, new GridConstraints(7, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        jugador2textField = new JTextField();
        panel3.add(jugador2textField, new GridConstraints(9, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        jugador3textField = new JTextField();
        panel3.add(jugador3textField, new GridConstraints(11, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Nombre del jugador 1");
        panel3.add(label5, new GridConstraints(4, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setText("Nombre del jugador 2");
        panel3.add(label6, new GridConstraints(6, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label7 = new JLabel();
        label7.setText("Nombre del jugador 3");
        panel3.add(label7, new GridConstraints(8, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label8 = new JLabel();
        label8.setText("Nombre del jugador 4");
        panel3.add(label8, new GridConstraints(10, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        String[] opcionesRondaInicialComboBox = {"1", "2", "3", "4","5","6"};
        rondaInicialComboBox = new JComboBox(opcionesRondaInicialComboBox);
        String[] opcionesRondaFinalComboBox = {"1", "2", "3", "4","5","6"};
        rondaFinalComboBox = new JComboBox(opcionesRondaFinalComboBox);
        String[] opcionesNroJugadoresComboBox = {"2", "3", "4"};
        nroJugadoresComboBox = new JComboBox(opcionesNroJugadoresComboBox);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        int nroJugadores = Integer.parseInt(nroJugadoresComboBox.getSelectedItem().toString());
        if (e.getSource() == volverAlMenúPrincipalButton) {

        }
        if (e.getSource() == comenzarLaPartidaButton) {

           if (Integer.parseInt(rondaFinalComboBox.getSelectedItem().toString()) - Integer.parseInt(rondaInicialComboBox.getSelectedItem().toString()) >= 0) {
                switch (nroJugadores) {
                    case 2:
                        if (!jugador1textField.getText().trim().equals("") && !jugador2textField.getText().trim().equals("")) {

                        } else {
                            JOptionPane.showMessageDialog(null, "Faltan nombres de jugadores");
                        }
                        break;
                    case 3:
                        if (!jugador1textField.getText().trim().equals("") && !jugador2textField.getText().trim().equals("") && !jugador3textField.getText().trim().equals("")) {

                        } else {
                            JOptionPane.showMessageDialog(null, "Faltan nombres de jugadores");
                        }
                        break;
                    case 4:
                        if (!jugador1textField.getText().trim().equals("") && !jugador2textField.getText().trim().equals("") && !jugador3textField.getText().trim().equals("") && !jugador4textField.getText().trim().equals("")) {

                        } else {
                            JOptionPane.showMessageDialog(null, "Faltan nombres de jugadores");
                        }
                        break;
                }
          } else {
                JOptionPane.showMessageDialog(null, "La ronda inicial no puede ser mayor que la final");
            }
        }
        bloquearJTextFields();

        if (e.getSource() == nroJugadoresComboBox) {
            nroJugadores = Integer.parseInt(nroJugadoresComboBox.getSelectedItem().toString());

        }

    }

    private void bloquearJTextFields() {

        if (Integer.parseInt(nroJugadoresComboBox.getSelectedItem().toString()) < 3) {
            jugador3textField.setText("");
            jugador3textField.setEditable(false);
        } else {
            jugador3textField.setEditable(true);
        }
        if (Integer.parseInt(nroJugadoresComboBox.getSelectedItem().toString()) < 4) {
            jugador4textField.setText("");
            jugador4textField.setEditable(false);
        } else {
            jugador4textField.setEditable(true);
        }
    }
}
