package com.lucas.Guis;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.lucas.Datos.GestorArchivos;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class TableroDePuntuaciones extends JFrame implements ActionListener {

    private JPanel panel1;
    private JButton volverPuntajesButton;
    private JLabel jugadorLabel;
    private JLabel puntajeLabel;

    public TableroDePuntuaciones() {
        $$$setupUI$$$();
        add(panel1);
        //    jugadorLabel.setText(Reglas.getNombreMejorPuntaje());
        //    puntajeLabel.setText(String.valueOf(Reglas.getMejorPuntaje()));
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.pack();
        GestorArchivos gestor = new GestorArchivos();
        try {
            if (gestor.leer("Carioca_Digital_Datos//jugadorMayor.txt").trim().equals("") || gestor.leer("Carioca_Digital_Datos//puntajeMayor.txt").trim().equals("")) {
                puntajeLabel.setVisible(false);

            } else {
                puntajeLabel.setText(gestor.leer("Carioca_Digital_Datos//puntajeMayor.txt"));
                jugadorLabel.setText(gestor.leer("Carioca_Digital_Datos//jugadorMayor.txt"));
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        volverPuntajesButton.addActionListener(this);

    }

    public static void main(String[] args) {
        GestorArchivos gestor = new GestorArchivos();

        gestor.escribir("Lucas", "jugadorMayor");
        gestor.escribir("25", "puntajeMayor");
        TableroDePuntuaciones aux = new TableroDePuntuaciones();
        aux.setVisible(true);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.setBackground(new Color(-14786275));
        panel1.setMinimumSize(new Dimension(1360, 680));
        panel1.setPreferredSize(new Dimension(1360, 680));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-14123225));
        panel1.add(panel2, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        label1.setForeground(new Color(-1));
        label1.setText("Mejor puntaje");
        panel2.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        volverPuntajesButton = new JButton();
        volverPuntajesButton.setText("Regresar al menú principal");
        panel2.add(volverPuntajesButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 4, new Insets(20, 20, 20, 20), -1, -1));
        panel3.setBackground(new Color(-14786275));
        panel1.add(panel3, BorderLayout.CENTER);
        puntajeLabel = new JLabel();
        puntajeLabel.setForeground(new Color(-1));
        puntajeLabel.setText("Label");
        panel3.add(puntajeLabel, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jugadorLabel = new JLabel();
        jugadorLabel.setForeground(new Color(-1));
        jugadorLabel.setText("Actualmente no hay ningún puntaje registrado en este equipo");
        panel3.add(jugadorLabel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel3.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel3.add(spacer2, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        String[] columnasPuntuacionesTable = {"Nombre", "Puntaje"};


    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == volverPuntajesButton) {
            this.setVisible(false);
            new MenuPrincipalGUI().setVisible(true);
            this.dispose();
        }
    }
}
